const LABELS: Record<string, string> = {
  price_to_tangible_book_vs_peer: 'P/Tangible BV vs peers',
  price_to_book_vs_peer: 'P/B vs peers',
  forward_pe_vs_trailing_pe: 'Forward P/E vs trailing P/E',
  dividend_yield_vs_5y_median: 'Dividend yield vs 5Y median',
  roe_vs_peer: 'ROE vs peers',
  roa_vs_peer: 'ROA vs peers',
  efficiency_ratio_trend_3y: 'Efficiency ratio trend (3Y)',
  cet1_or_tier1_capital_vs_requirement: 'CET1 / Tier 1 vs requirement',
  npl_or_asset_quality_trend: 'NPL / asset quality trend',
  tangible_common_equity_ratio: 'Tangible common equity ratio',
  ocf_to_ni_ttm: 'Operating cash flow / net income (TTM)',
  piotroski_f_score: 'Piotroski F-Score',
  combined_ratio_level_and_trend: 'Combined ratio level & trend',
  spread_or_investment_margin_proxy: 'Spread / investment margin proxy',
  reserve_strength_proxy: 'Reserve strength proxy',
  debt_to_capital: 'Debt / capital',
  interest_coverage: 'Interest coverage',
  ev_to_ebitda_vs_peer: 'EV/EBITDA vs peers',
  ev_to_ebit_vs_peer: 'EV/EBIT vs peers',
  fcf_yield_vs_peer: 'FCF yield vs peers',
  operating_margin_vs_peer: 'Operating margin vs peers',
  net_cash_to_revenue_or_aum_proxy: 'Net cash / revenue (or AUM proxy)',
  price_to_affo_or_ffo_vs_peer: 'P/AFFO or P/FFO vs peers',
  same_store_noi_growth_or_affo_growth: 'Same-store NOI or AFFO growth',
  net_debt_to_ebitda_reit_definition: 'Net debt / EBITDA (REIT definition)',
  secured_debt_ratio_or_maturity_wall_proxy: 'Secured debt / maturity wall proxy',
  roe_vs_allowed_return_proxy: 'ROE vs allowed return proxy',
  net_debt_to_ebitda: 'Net debt / EBITDA',
  ocf_to_capex_coverage: 'OCF / capex coverage',
  fcf_yield_vs_own_5y_median: 'FCF yield vs own 5Y median',
  roic_vs_peer: 'ROIC vs peers',
  ebitda_margin_vs_peer: 'EBITDA margin vs peers',
  fcf_positive_ttm: 'Free cash flow (TTM)',
  peg_ttm: 'PEG (TTM)',
  gross_margin_stability_3y: 'Gross margin stability (3Y)',
  backlog_growth_proxy: 'Backlog growth proxy',
  eps_yoy_growth_2_of_3: 'EPS YoY growth in ≥2 of last 3 years',
  ev_to_gross_profit_vs_peer: 'EV / gross profit vs peers',
  ev_to_revenue_vs_peer: 'EV / revenue vs peers',
  rule_of_40: 'Rule of 40',
}

export function metricLabel(id: string): string {
  return LABELS[id] ?? id.replace(/_/g, ' ')
}
