/** How `company_moat_summaries.content_source` was produced. */
export const MOAT_CONTENT_SOURCES = ['curated', 'auto_generated'] as const
export type MoatContentSource = (typeof MOAT_CONTENT_SOURCES)[number]

export function isAutoGeneratedMoatContent(source: string | null | undefined): boolean {
  return source === 'auto_generated'
}
